### PR TITLE
Don't add Dynamic routes

### PR DESCRIPTION
**Pull request by RehanSaeed**
Fixes https://github.com/rishabh3112/gridsome-plugin-pwa/issues/36

### CODE REVIEW

**Comment by rishabh3112** [comment]
@RehanSaeed this is not the intended solution. We need to filter the just the dynamic routes not all routes. This will result in nothing being added to templatedURLs.

**Comment by RehanSaeed** [comment]
That was not the case for me. I still had all html, json files and images added.

**Comment by RehanSaeed** [comment]
Ah! I guess we have to add the `/foo/index.html` files and `/foo/` to the cached list, just in case, someone visits the site with our without the `.html` file extension.

**Comment by RehanSaeed** [comment]
@rishabh3112 Looked at this some more. I don't know what I'm doing with Workbox, so I'll leave that to you. Right now, this plugin is broken without fixing https://github.com/rishabh3112/gridsome-plugin-pwa/issues/36.

**Pull request closed without merging**
