### PR TITLE
File customization and bug fix

### PR DESCRIPTION
**Pull request by Matthew-Kanderka**
Auto-generated client.json is now ignored when creating the service-worker, was causing an error before. Also added a new option that contains a custom list for the files the user wants cached.

### CODE REVIEW

**Comment by rishabh3112** [comment]
Thanks for the pull request btw :)

**Comment by Matthew-Kanderka** [comment]
Yes I tested this and it works great!

**Comment by Matthew-Kanderka** [comment]
If you need any more help I am glad to help out.

**Comment by rishabh3112** [comment]
Thanks!

**Pull request merged**
